### ISSUE TITLE
Only see output when out = 0 and unknown otherwise

### ISSUE THREAD

**Issue by nspahn** [nspahn/413Lab7#1]
i think  its probably in the forwarding unit logic.

**Comment by SnrNotHere16** [comment]
Hey, I simulated your code and found some things that may help. 
My approach was to discover the first instance when you encountered the red signals. 
![image](https://user-images.githubusercontent.com/24782454/99126005-27fd7980-25ba-11eb-9358-4c95d33979eb.png)
From your image, the first forcing unknown (red signal)  occurs  at 165 nanoseconds. 
So I backtracked and looked at every wire to see where the forcing unknown originated from. 
![image](https://user-images.githubusercontent.com/24782454/99126502-21233680-25bb-11eb-8489-a4314e0b3a49.png)
Since out was set equal to WriteBackData, I decided to look where WriteBackData gets it's values from. 
![image](https://user-images.githubusercontent.com/24782454/99126569-487a0380-25bb-11eb-9733-37380400b667.png)
From here, I looked at the inputs and of this module and found they were also forcing unknown
![image](https://user-images.githubusercontent.com/24782454/99127096-58461780-25bc-11eb-98d3-1fc02f24755e.png)
After I looked where did the inputs receive their values and kept backtracking this way. 
I eventually ended up at this module 
![image](https://user-images.githubusercontent.com/24782454/99127308-d60a2300-25bc-11eb-8d91-92f4a8ded818.png)
Looking at the inputs on the waveform, I found something interesting. 
![image](https://user-images.githubusercontent.com/24782454/99127787-030b0580-25be-11eb-95fc-523a023a9a1f.png)
I found a forcing red that predates your original forcing red. So I looked at instances where FwdMux2Out was an output. 
![image](https://user-images.githubusercontent.com/24782454/99127923-567d5380-25be-11eb-8e59-168130723caf.png)
![image](https://user-images.githubusercontent.com/24782454/99127944-62691580-25be-11eb-81de-de3c6794ddba.png)
In both these modules, FwdMux2Out is an output. I have never thought about this but this seems strange because the output is being changed in two instances. So I looked at the modules where FwdMux2Out was an output on the waveform 
![image](https://user-images.githubusercontent.com/24782454/99128831-c391e880-25c0-11eb-814d-ef026ab7df3a.png)
The brown signals indicate FwdMux2Out but they are different in value. 
However, I am a novice so I don't know but it raised a red flag. So the next idea I had was to comment out one of these modules. 
![image](https://user-images.githubusercontent.com/24782454/99128170-fe931c80-25be-11eb-917e-927060754b9e.png)
![image](https://user-images.githubusercontent.com/24782454/99129048-5a5ea500-25c1-11eb-802e-72f6cff59139.png)
The result was your original results from your prelab. I don't know what your expected results are but the issue is from FwdMux2Out.

**Comment by nspahn** [comment]
Thank you so much for your help. Architecture is hard to wrap my head around, so I appreciate the time you invested to help explain this.
